# action.yml
name: 'Sharpen docker action'
description: 'Conversion from Java to C# using mono/sharpen converter'
author: "Javier Tuya"
branding:
  icon: hash
  color: blue
inputs:
  working-dir:
    description: 'Directory from which sharpen will be run'
    required: false
    default: '.'
  project-dir:
    description: 'Directory that contains the java source code to be converted'
    required: true
  sharpen-args:
    description: 'Additional arguments to be passed to sharpen'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.working-dir }}
    - ${{ inputs.project-dir }}
    - ${{ inputs.sharpen-args }}
    