name: Test sharpen-action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Convert test project to C#
        uses: javiertuya/sharpen-action
        with:
          working-dir: 'test'
          project-dir: 'src/main/java'
          args: '@sharpen-all-options.txt'

      - name: Check converted files
        run: mvn test --no-transfer-progress
