name: Test sharpen-action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Convert test project to C#
        uses: javiertuya/sharpen-action@main
        with:
          working-dir: 'test'
          project-dir: 'src/main/java'
          sharpen-args: '@sharpen-all-options.txt'
      - name: Test converted files
        run: cd test && mvn test --no-transfer-progress -Dmaven.test.failure.ignore=true
      - name: Pubish test report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: test-report
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          fail_on_test_failures: 'true'
      - name: Publish converted sources & test report files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: converted sources & test reports
          path: |
            test/src/main/main.net
            test/target/surefire-reports
