name: Test sharpen-action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Convert test project to C#
        uses: javiertuya/sharpen-action@main
        with:
          working-dir: 'test'
          project-dir: 'src/main/java'
          sharpen-args: '@sharpen-all-options.txt'
      - name: Check converted files
        run: cd test && mvn test --no-transfer-progress #-Dmaven.test.failure.ignore=true
      - name: Publish converted sources & test reports
        uses: actions/upload-artifact@v2
        with:
          name: converted sources & test reports
          path: |
            test/src/main/main.net
            test/target/surefire-reports
